version: '3'
services: 
    app:
        build: ./
        environment:
            - DISPLAY=:0
            - TZ=Asia/Tokyo
            - USERNAME=${USERNAME}
            - USEREMAIL=${USEREMAIL}
        volumes:
            - ./:/home/python/app